meta_product_name: "Miss Cocktail"
meta_title: "Miss Cockatail - find cocktail recipes"
meta_description: "Miss Cockatail - find cocktail recipes"
meta_image: "cover.png" # should exist in `app/assets/images/`
