meta_product_name: "Mr Cocktail"
meta_title: "Mr Cocktail - cocktail recipe library"
meta_description: "Browse through a variety of cocktail recipes, add your own mixtures and leave a review!"
meta_image: "cover.png" # should exist in `app/assets/images/`
