meta_product_name: "Mr Cocktail"
meta_title: "Mr Cocktail - cocktail recipe library"
meta_description: "Mr Cocktail - cocktail recipe library. Browse through a variety of coktail recipes and add your own!"
meta_image: "cover.png" # should exist in `app/assets/images/`
