meta_product_name: "Mr Cocktail"
meta_title: "Mr Conktail - cocktail recipe library"
meta_description: "Mr Conktail - cocktail recipe library"
meta_image: "cover.png" # should exist in `app/assets/images/`
